[mgr]
scrolloff = 8

show_hidden = true

sort_by = "btime"
sort_reverse = true

linemode = "size_and_mtime"


[preview]
wrap = "yes"
# Change them to your desired values
max_width  = 1000
max_height = 1000
