[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/conf.d/colors.conf'
post_hook = 'hyprctl reload config-only &>/dev/null'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs &>/dev/null'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/matugen/waybar_launch.sh &>/dev/null'

[templates.zsh]
input_path = '~/.config/matugen/templates/zsh-colors.zsh'
output_path = '~/.config/zsh/colors.zsh'
post_hook = "pkill -USR1 -x zsh"
